export const SET_CURRENT_ACCOUNT = 'olipie/App/SET_CURRENT_ACCOUNT';
export const SET_CURRENT_USER = 'olipie/App/SET_CURRENT_USER';
export const SHOW_SEARCH_BAR = 'SHOW_SEARCH_BAR';
export const SET_IS_SEARCHING = 'SET_IS_SEARCHING';